#!/usr/local/bin/perl

use Finance::YahooQuote;

die "Usage: $0 symbol [symbol ...]" if $#ARGV == -1;

@h = (	"Symbol","Name","Last","Trade Date","Trade Time","Change","% Change",
	"Volume","Avg. Daily Volume","Bid","Ask","Prev. Close","Open",
	"Day's Range","52-Week Range","EPS","P/E Ratio","Div. Pay Rate",
	"Div/Share","Div. Yield","Mkt. Cap"  );

@q = getquote(@ARGV);

foreach $a (@q) {
  foreach (0..$#h) {
      print "$h[$_]: $$a[$_]\n";
  }
  print "\n";
}
